"""Integration tests for the OnboardingCoordinator."""

import pytest
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

from kortex_mcp.coordinators.onboarding import (
    OnboardingCoordinator,
    OnboardingResult,
    RegenerateResult,
)
from kortex_mcp.generators.structure_generator import StructureMemoryGenerator
from kortex_mcp.generators.tech_stack_generator import TechStackMemoryGenerator
from kortex_mcp.generators.architecture_generator import ArchitectureMemoryGenerator


# Expected memory IDs generated by the coordinator
EXPECTED_MEMORY_IDS = [
    "project_structure",
    "tech_stack",
    "architecture",
    "dependencies",
    "android_platform",
    "ios_platform",
    "coding_patterns",
    "testing_setup",
]


@pytest.fixture
def sample_kmp_path(fixtures_dir: Path, tmp_path: Path) -> Path:
    """Get path to sample KMP project fixture (copied to temp dir).

    Args:
        fixtures_dir: Fixtures directory path
        tmp_path: Temporary directory path

    Returns:
        Path to sample KMP project in temp dir
    """
    import shutil
    source = fixtures_dir / "sample_kmp_project"
    dest = tmp_path / "sample_kmp_project"
    shutil.copytree(source, dest)
    return dest


@pytest.fixture
def sample_cmp_path(fixtures_dir: Path, tmp_path: Path) -> Path:
    """Get path to sample CMP project fixture (copied to temp dir).

    Args:
        fixtures_dir: Fixtures directory path
        tmp_path: Temporary directory path

    Returns:
        Path to sample CMP project in temp dir
    """
    import shutil
    source = fixtures_dir / "sample_cmp_project"
    dest = tmp_path / "sample_cmp_project"
    shutil.copytree(source, dest)
    return dest


@pytest.fixture
async def coordinator(tmp_path: Path) -> OnboardingCoordinator:
    """Create an OnboardingCoordinator with a temporary storage directory.

    Args:
        tmp_path: Temporary directory path

    Returns:
        Initialized OnboardingCoordinator instance
    """
    coord = OnboardingCoordinator(tmp_path)
    await coord.initialize()
    return coord


class TestOnboardingCoordinator:
    """Test cases for OnboardingCoordinator functionality."""

    @pytest.mark.asyncio
    async def test_coordinator_initialization(self, tmp_path: Path) -> None:
        """Verify coordinator initializes with all analyzers and generators."""
        coordinator = OnboardingCoordinator(tmp_path)
        
        # Should have 8 analyzers registered
        assert len(coordinator.analyzers) == 8
        
        # Should have 8 generators registered
        assert len(coordinator.generators) == 8
        
        # All expected memory IDs should be present
        available = coordinator.get_available_memories()
        for memory_id in EXPECTED_MEMORY_IDS:
            assert memory_id in available, f"Missing memory ID: {memory_id}"
        
        # Coordinator should not be initialized yet (initialize() not called)
        assert coordinator._initialized is False
        
        # After initialization
        await coordinator.initialize()
        assert coordinator._initialized is True
        
        # Memory store should be accessible
        assert coordinator._memory_store is not None

    @pytest.mark.asyncio
    async def test_full_onboarding_kmp_project(
        self, sample_kmp_path: Path
    ) -> None:
        """Full onboarding of KMP project, verify all memories generated."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        result = await coordinator.onboard()
        
        # Onboarding should succeed
        assert result.success is True
        assert result.project_name == "sample_kmp_project"
        
        # Should generate memories (may not be all 8 if some analyzers find no data)
        assert len(result.memories_generated) > 0
        
        # No critical errors
        assert len(result.errors) == 0
        
        # Memory files should exist
        memory_dir = sample_kmp_path / ".kortex" / "memories"
        assert memory_dir.exists()

    @pytest.mark.asyncio
    async def test_full_onboarding_cmp_project(
        self, sample_cmp_path: Path
    ) -> None:
        """Full onboarding of CMP project."""
        coordinator = OnboardingCoordinator(sample_cmp_path)
        await coordinator.initialize()
        
        result = await coordinator.onboard()
        
        # Onboarding should succeed
        assert result.success is True
        assert result.project_name == "sample_cmp_project"
        
        # Should generate memories
        assert len(result.memories_generated) > 0
        
        # No critical errors
        assert len(result.errors) == 0

    @pytest.mark.asyncio
    async def test_onboard_returns_success(
        self, sample_kmp_path: Path
    ) -> None:
        """Verify onboard() returns an OnboardingResult with success=True."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        result = await coordinator.onboard()
        
        # Should return OnboardingResult instance
        assert isinstance(result, OnboardingResult)
        assert result.success is True
        assert isinstance(result.memories_generated, list)
        assert isinstance(result.errors, list)
        assert isinstance(result.warnings, list)

    @pytest.mark.asyncio
    async def test_onboard_generates_all_memories(
        self, sample_kmp_path: Path
    ) -> None:
        """Verify all 8 memory types are generated."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        result = await coordinator.onboard()
        
        # All 8 memory types should be generated
        assert len(result.memories_generated) == 8
        
        for memory_id in EXPECTED_MEMORY_IDS:
            assert memory_id in result.memories_generated, (
                f"Memory '{memory_id}' was not generated"
            )

    @pytest.mark.asyncio
    async def test_onboard_handles_missing_directory(
        self, tmp_path: Path
    ) -> None:
        """Error handling for invalid/non-existent project path."""
        non_existent_path = tmp_path / "non_existent_project"
        
        coordinator = OnboardingCoordinator(non_existent_path)
        await coordinator.initialize()
        
        result = await coordinator.onboard()
        
        # Should handle gracefully - either with errors or empty results
        # The coordinator should not crash
        assert isinstance(result, OnboardingResult)
        # Project name should still be set from the path
        assert result.project_name == "non_existent_project"

    @pytest.mark.asyncio
    async def test_onboard_requires_initialization(
        self, tmp_path: Path
    ) -> None:
        """Verify onboard() raises error if not initialized."""
        coordinator = OnboardingCoordinator(tmp_path)
        
        # Should raise RuntimeError if not initialized
        with pytest.raises(RuntimeError, match="not initialized"):
            await coordinator.onboard()

    @pytest.mark.asyncio
    async def test_regenerate_memory(
        self, sample_kmp_path: Path
    ) -> None:
        """Test regenerating a specific memory."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        # First do full onboarding
        await coordinator.onboard()
        
        # Now regenerate a specific memory
        result = await coordinator.regenerate_memory("project_structure")
        
        assert isinstance(result, RegenerateResult)
        assert result.success is True
        assert result.memory_id == "project_structure"
        assert result.error is None

    @pytest.mark.asyncio
    async def test_regenerate_nonexistent_memory(
        self, sample_kmp_path: Path
    ) -> None:
        """Error handling for invalid memory_id in regenerate_memory."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        # Try to regenerate a non-existent memory
        result = await coordinator.regenerate_memory("nonexistent_memory")
        
        assert isinstance(result, RegenerateResult)
        assert result.success is False
        assert result.memory_id == "nonexistent_memory"
        assert result.error is not None
        assert "No generator registered" in result.error

    @pytest.mark.asyncio
    async def test_regenerate_memory_requires_initialization(
        self, tmp_path: Path
    ) -> None:
        """Verify regenerate_memory() raises error if not initialized."""
        coordinator = OnboardingCoordinator(tmp_path)
        
        # Should raise RuntimeError if not initialized
        with pytest.raises(RuntimeError, match="not initialized"):
            await coordinator.regenerate_memory("project_structure")

    @pytest.mark.asyncio
    async def test_get_available_memories(self, tmp_path: Path) -> None:
        """Test listing available memory IDs."""
        coordinator = OnboardingCoordinator(tmp_path)
        
        # Should work even before initialization
        available = coordinator.get_available_memories()
        
        assert isinstance(available, list)
        assert len(available) == 8
        
        # All expected memory IDs should be present
        for memory_id in EXPECTED_MEMORY_IDS:
            assert memory_id in available

    @pytest.mark.asyncio
    async def test_register_custom_analyzer(self, tmp_path: Path) -> None:
        """Test registering a custom analyzer."""
        from kortex_mcp.analyzers.base import BaseAnalyzer, AnalysisResult
        
        class CustomAnalyzer(BaseAnalyzer):
            @property
            def name(self) -> str:
                return "custom_analyzer"
            
            async def analyze(self) -> AnalysisResult:
                return AnalysisResult(
                    analyzer_name=self.name,
                    success=True,
                    data={"custom": "data"},
                    errors=[],
                    warnings=[],
                )
            
            def get_memory_category(self) -> str:
                return "custom_analysis"
        
        coordinator = OnboardingCoordinator(tmp_path)
        initial_count = len(coordinator.analyzers)
        
        coordinator.register_analyzer(CustomAnalyzer(tmp_path))
        
        assert len(coordinator.analyzers) == initial_count + 1

    @pytest.mark.asyncio
    async def test_register_custom_generator(self, tmp_path: Path) -> None:
        """Test registering a custom generator."""
        from kortex_mcp.generators.base import BaseMemoryGenerator
        
        class CustomGenerator(BaseMemoryGenerator):
            @property
            def memory_id(self) -> str:
                return "custom"
            
            @property
            def memory_title(self) -> str:
                return "Custom Memory"
            
            @property
            def memory_category(self) -> str:
                return "other"
            
            def generate_content(self, analysis_data: dict) -> dict:
                return {"custom": "content"}
            
            def to_markdown(self, memory_data: dict) -> str:
                return "# Custom Memory\n\nCustom content"
        
        coordinator = OnboardingCoordinator(tmp_path)
        
        coordinator.register_generator("custom", CustomGenerator())
        
        available = coordinator.get_available_memories()
        assert "custom" in available

    @pytest.mark.asyncio
    async def test_memory_store_property_before_init(
        self, tmp_path: Path
    ) -> None:
        """Test accessing memory_store before initialization raises error."""
        coordinator = OnboardingCoordinator(tmp_path)
        
        with pytest.raises(RuntimeError, match="not initialized"):
            _ = coordinator.memory_store

    @pytest.mark.asyncio
    async def test_initialize_idempotent(self, tmp_path: Path) -> None:
        """Test that calling initialize() multiple times is safe."""
        coordinator = OnboardingCoordinator(tmp_path)
        
        await coordinator.initialize()
        first_store = coordinator._memory_store
        
        # Calling initialize again should be a no-op
        await coordinator.initialize()
        
        # Should be the same store instance
        assert coordinator._memory_store is first_store


class TestMemoryGeneration:
    """Test cases for memory content generation."""

    def test_structure_memory_content(self) -> None:
        """Verify structure memory has expected fields."""
        generator = StructureMemoryGenerator()
        
        analysis_data = {
            "project_name": "TestProject",
            "project_type": "Kotlin Multiplatform (KMP)",
            "kotlin_version": "1.9.0",
            "compose_version": "1.5.0",
            "gradle_version": "8.0",
            "modules": [
                {
                    "name": "shared",
                    "type": "Library",
                    "targets": ["android", "ios"],
                }
            ],
            "source_sets": [
                {
                    "name": "commonMain",
                    "type": "Common",
                    "path": "src/commonMain",
                    "dependencies": [],
                    "depends_on": [],
                }
            ],
            "build_targets": [
                {"target": "android", "platform": "Android"},
                {"target": "iosArm64", "platform": "iOS"},
            ],
            "build_files": ["build.gradle.kts", "settings.gradle.kts"],
        }
        
        content = generator.generate_content(analysis_data)
        
        # Verify structure has expected sections
        assert "overview" in content
        assert "modules" in content
        assert "source_sets" in content
        assert "build_targets" in content
        assert "build_files" in content
        
        # Verify overview content
        overview = content["overview"]
        assert overview["project_name"] == "TestProject"
        assert overview["project_type"] == "Kotlin Multiplatform (KMP)"
        assert overview["kotlin_version"] == "1.9.0"
        
        # Verify modules content
        assert len(content["modules"]) == 1
        assert content["modules"][0]["name"] == "shared"
        
        # Verify source sets content
        assert len(content["source_sets"]) == 1
        assert content["source_sets"][0]["name"] == "commonMain"

    def test_structure_memory_empty_data_raises(self) -> None:
        """Verify StructureMemoryGenerator raises on empty data."""
        generator = StructureMemoryGenerator()
        
        with pytest.raises(ValueError, match="empty"):
            generator.generate_content({})
        
        # Test with None (type: ignore for type checker)
        with pytest.raises(ValueError, match="empty"):
            generator.generate_content(None)  # type: ignore[arg-type]

    def test_tech_stack_memory_content(self) -> None:
        """Verify tech stack memory format."""
        generator = TechStackMemoryGenerator()
        
        analysis_data = {
            "project_type": "KMP",
            "languages": ["Kotlin", "Swift"],
            "frameworks": ["Compose Multiplatform", "UIKit"],
            "libraries": [
                {"name": "ktor", "version": "2.3.0"},
                {"name": "kotlinx-serialization", "version": "1.6.0"},
            ],
            "build_tools": ["Gradle"],
            "kotlin_version": "1.9.0",
        }
        
        content = generator.generate_content(analysis_data)
        
        # Verify content structure (fields depend on generator implementation)
        assert content is not None
        assert isinstance(content, dict)

    def test_architecture_memory_content(self) -> None:
        """Verify architecture memory format."""
        generator = ArchitectureMemoryGenerator()
        
        analysis_data = {
            "architecture_patterns": ["MVVM", "Clean Architecture"],
            "layers": ["presentation", "domain", "data"],
            "dependency_injection": "Koin",
            "navigation": "Compose Navigation",
        }
        
        content = generator.generate_content(analysis_data)
        
        # Verify content structure
        assert content is not None
        assert isinstance(content, dict)

    def test_memory_markdown_output(self) -> None:
        """Verify markdown conversion works."""
        generator = StructureMemoryGenerator()
        
        memory_data = {
            "overview": {
                "project_name": "TestProject",
                "project_type": "KMP",
                "kotlin_version": "1.9.0",
                "compose_version": None,
                "gradle_version": "8.0",
            },
            "modules": [
                {"name": "app", "type": "Application", "targets": ["android"]}
            ],
            "source_sets": [],
            "build_targets": [],
            "build_files": ["build.gradle.kts"],
        }
        
        markdown = generator.to_markdown(memory_data)
        
        # Verify markdown output
        assert isinstance(markdown, str)
        assert "# Project Structure: TestProject" in markdown
        assert "**Project Type:**" in markdown
        assert "KMP" in markdown
        assert "**Kotlin Version:** 1.9.0" in markdown

    def test_memory_markdown_empty_data_raises(self) -> None:
        """Verify to_markdown raises on empty data."""
        generator = StructureMemoryGenerator()
        
        with pytest.raises(ValueError, match="empty"):
            generator.to_markdown({})
        
        # Test with None (type: ignore for type checker)
        with pytest.raises(ValueError, match="empty"):
            generator.to_markdown(None)  # type: ignore[arg-type]


class TestOnboardingIntegration:
    """Integration tests for the complete onboarding flow."""

    @pytest.mark.asyncio
    async def test_onboarding_creates_kortex_directory(
        self, sample_kmp_path: Path
    ) -> None:
        """Verify onboarding creates .kortex directory structure."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        await coordinator.onboard()
        
        # .kortex directory should exist
        kortex_dir = sample_kmp_path / ".kortex"
        assert kortex_dir.exists()
        
        # memories subdirectory should exist
        memories_dir = kortex_dir / "memories"
        assert memories_dir.exists()

    @pytest.mark.asyncio
    async def test_onboarding_memories_are_persisted(
        self, sample_kmp_path: Path
    ) -> None:
        """Verify generated memories are persisted to disk."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        result = await coordinator.onboard()
        
        # Get the memory store
        memory_store = coordinator.memory_store
        
        # All generated memories should be retrievable
        for memory_id in result.memories_generated:
            memory = await memory_store.get(memory_id)
            assert memory is not None, f"Memory '{memory_id}' not persisted"

    @pytest.mark.asyncio
    async def test_onboarding_result_structure(
        self, sample_kmp_path: Path
    ) -> None:
        """Verify OnboardingResult has correct structure."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        result = await coordinator.onboard()
        
        # Verify all fields are present
        assert hasattr(result, "success")
        assert hasattr(result, "project_name")
        assert hasattr(result, "memories_generated")
        assert hasattr(result, "errors")
        assert hasattr(result, "warnings")
        
        # Verify field types
        assert isinstance(result.success, bool)
        assert isinstance(result.project_name, str)
        assert isinstance(result.memories_generated, list)
        assert isinstance(result.errors, list)
        assert isinstance(result.warnings, list)

    @pytest.mark.asyncio
    async def test_regenerate_preserves_other_memories(
        self, sample_kmp_path: Path
    ) -> None:
        """Verify regenerating one memory doesn't affect others."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        # Initial onboarding
        initial_result = await coordinator.onboard()
        initial_memories = set(initial_result.memories_generated)
        
        # Regenerate one memory
        await coordinator.regenerate_memory("project_structure")
        
        # Get all memories from store
        memory_store = coordinator.memory_store
        all_memories = await memory_store.get_all()
        
        # Should still have all the initial memories
        stored_ids = {m.id for m in all_memories}
        for memory_id in initial_memories:
            assert memory_id in stored_ids, (
                f"Memory '{memory_id}' was lost after regeneration"
            )

    @pytest.mark.asyncio
    async def test_double_onboarding_updates_memories(
        self, sample_kmp_path: Path
    ) -> None:
        """Verify running onboard twice updates existing memories."""
        coordinator = OnboardingCoordinator(sample_kmp_path)
        await coordinator.initialize()
        
        # First onboarding
        result1 = await coordinator.onboard()
        
        # Second onboarding (should update, not fail)
        result2 = await coordinator.onboard()
        
        # Both should succeed
        assert result1.success is True
        assert result2.success is True
        
        # Should generate same memories
        assert set(result1.memories_generated) == set(result2.memories_generated)
